services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: code-server
    ports:
      - "8080:8080"
    volumes:
      - coder-home:/home/opt
      - /mnt/data/dev:/data/dev
    restart: unless-stopped

volumes:
  coder-home: